### <a name='0'></a>Import biblioteki

In [ ]:
import numpy as np

np.__version__

### <a name='3'></a> Ćwiczenie 21
Wygeneruj i przekształć poniższą tablicę numpy na listę.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



__Wskazówka:__ Użyj metody _np.array.tolist()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='4'></a> Ćwiczenie 22
Podana jest poniższa tablica numpy:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Używając operatora wycinania przekształć tablicę w poniższe:

* zamiana wierszy (pierwszy z ostatnim)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```







In [ ]:
# tutaj wpisz rozwiązanie

* zamiana kolumn (odwrócona kolejność)


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```


In [ ]:
# tutaj wpisz rozwiązanie

* zamiana wierszy i kolumn (odwrócone kolejności)


```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```       

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='6'></a> Ćwiczenie 26
Podaną poniżej tablicę numpy:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
Przekształć na tablicę:


```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```
__Wskazówka:__ Użyj operatora wycinania oraz przypisz odpowiednie wartości.





In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 23
Połącz podane poniżej tablice $A$ oraz $B$ w jedną.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```




__Oczekiwany rezultat:__


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```
__Wskazówka:__ Użyj funkcji _np.append()_.


In [ ]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 24
Podana jest poniższa tablica numpy $A$.
Znajdź unikalne wartości tej tablicy.


```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```


__Wskazówka:__ Użyj funkcji _np.unique()_.

In [ ]:
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='10'></a> Ćwiczenie 25
Podana jest poniższa tablica:


```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```



Zwróć indeksy na których stoją maksymalne wartości dla danego wiersza.

__Wskazówka:__ Użyj funkcji _np.argmax()_.

In [ ]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='1'></a> Ćwiczenie 26
Wykonaj dwa sortowania podanej poniżej tablicy $A$:
* wierszowo (rosnąco)
* kolumnowo (rosnąco)


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.sort()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [1]:
# tutaj wpisz rozwiązanie

### <a name='2'></a> Ćwiczenie 27
Wytnij wszystkie elementy tablicy $A$ o wartości wyższej niż 8.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```


In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='3'></a> Ćwiczenie 28
Podana jest poniższa tablica $A$. Zastąp elementy powyżej wartości 10 wartością stałą 10 (obcięcie wartości do 10).


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Wskazówka:__ Użyj funkcji _np.where()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='4'></a> Ćwiczenie 29
Poniższą dwuwymiarową tablicę $A$ przedstaw w postaci 'wypłaszczonej' jednowymiarowej tablicy.  

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```



__Oczekiwany wynik:__


```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

__Wskazówka:__ Użyj funkcji _np.ravel()_.




In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='5'></a> Ćwiczenie 30
Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 0.0.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Oczekiwany wynik:__


```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```





__Wskazówka:__ Użyj funkcji _np.zeros_like()_.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [2]:
# tutaj wpisz rozwiązanie