### <a name='0'></a>Import biblioteki

In [3]:
import numpy as np

np.__version__

'1.24.3'

### <a name='6'></a> Ćwiczenie 31

Zbuduj tablicę o identycznym kształcie i typie danych jak tablica $A$ oraz wypełnij ją stałą wartością 9.99.


```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

__Oczekiwany wynik:__


```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```



__Wskazówka:__ Użyj funkcji _np.full_like()_.

In [4]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

In [5]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 32
Stwórz dowolną tablicę 3-wymiarową o kształcie $(2, 3, 4)$.

In [6]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 33

Wygeneruj dwuwymiarową tablicę o kształcie _(200, 300)_ wypełnioną wartościami losowymi od 0 do 255 włacznie i typie danych _np.uint8_ i przypisz do zmiennej _image_.

__Wskazówka:__ Użyj funkcji _np.random.randint()_.

In [7]:
# tutaj wpisz rozwiązanie

Nastepnie uruchom poniższy blok kodu. W rezultacie uzyskasz podgląd na losowo wygenerowany czarno-biały obraz.

In [8]:
#!pip install opencv-python

In [ ]:
import cv2
from matplotlib import pyplot as plt
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.show()

### <a name='10'></a> Ćwiczenie 34
Tablicę _image_ z poprzedniego zadania posortuj wzdłuż wiersza rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

Tablicę _image_ z poprzedniego zadania posortuj wzdłuż kolumny rosnąco. Następnie dzięki funkcji _cv2_imshow()_ wyświetl otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='1'></a> Ćwiczenie 35
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [ ]:
# tutaj wpisz rozwiązanie

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='2'></a> Ćwiczenie 36
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```


In [ ]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='3'></a> Ćwiczenie 37
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [ ]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 38
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Wskazówka:__ Wykorzystaj funkcję _np.set_printoptions() z argumentami `suppress` oraz `precision`_.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```

In [ ]:
A = np.array([1.2e-6, 1.7e-7])

### <a name='2'></a> Ćwiczenie 39
Podane są poniższe dwie tablice $A$ i $B$:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Pomnóż tablice przez siebie - element po elemencie (element-wise).

In [ ]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

### <a name='3'></a> Ćwiczenie 40
Podana jest poniższa tablica $A$:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Wyznacz pierwiastek z każdego elementu tablicy $A$.

__Wskazówka:__ Użyj funkcji _np.sqrt()_.

In [ ]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])