### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

Bad value in file PosixPath('/Users/tomasz/.matplotlib/stylelib/company.mplstyle'), line 3 ("axes.prop_cycle: cycler('color', ['#123D98', '#C21E3C', '#E2A713', '#00AEEF', '#7F3F98'])"): Key axes.prop_cycle: "cycler('color', ['" is not a valid cycler construction: EOL while scanning string literal (<unknown>, line 1)
Bad value in file PosixPath('/Users/tomasz/.matplotlib/stylelib/company.mplstyle'), line 6 ('grid.color: #e0e0e0'): Key grid.color: '' does not look like a color arg


#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-2.586165378844002,
 -1.8508217640198326,
 -1.5800213039605882,
 -1.5160157159793997,
 -0.9363050948477892,
 -0.8837940494356215,
 -0.8683083252935028,
 -0.8301318171925318,
 -0.778686308643596,
 -0.6773636812693943,
 -0.6412418804817174,
 -0.5658621033527811,
 -0.5428769438263885,
 -0.5085269811413605,
 -0.4327557172445756,
 -0.39700576239416013,
 -0.3380920902650593,
 -0.3054731427162159,
 -0.19870468779051118,
 -0.08336076133225985,
 -0.07686287499189257,
 -0.06914310996542078,
 -0.05545657784671823,
 -0.04256965284674551,
 0.03837475182480885,
 0.199001113194076,
 0.2304975469762981,
 0.23714595853983533,
 0.2879445839306373,
 0.3041699620292996,
 0.30882907245937774,
 0.37131058939801875,
 0.42779326704260107,
 0.46840740685034493,
 0.528718866827865,
 0.5348752655416111,
 0.5959840359479683,
 0.7583589866800703,
 0.7890711789525046,
 0.8831200361782611,
 0.9548782189845887,
 0.9603544003648135,
 1.0227139146627255,
 1.0838362331273135,
 1.1280849278331055,
 1.141810319079239,
 1

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.038375, 0.199001, 0.230498, 0.237146, 0.287945, 0.30417 ,
       0.308829, 0.371311, 0.427793, 0.468407, 0.528719, 0.534875,
       0.595984, 0.758359, 0.789071, 0.88312 , 0.954878, 0.960354,
       1.022714, 1.083836, 1.128085, 1.14181 , 1.169686, 1.256477,
       1.360925, 1.924653])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.586165            0.0
1 -1.850822            0.0
2 -1.580021            0.0
3 -1.516016            0.0
4 -0.936305            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'data=%{x}<br>max_relu_data=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': ('o3VheXewBMAaCzNI95z9v27nN2vER/' ... 'KHGvQ/EIJ8ilnG9T8/r4NQYcv+Pw=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'KHGvQ/EIJ8ilnG9T8/r4NQYcv+Pw=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'height': 400,
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'ReLU Function'},
               'width': 700,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'data'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'max_relu_data'}}}
})

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.283256235506769,
 -5.910502648985309,
 -4.382131279604284,
 -4.256150396652934,
 -3.634117914311369,
 -3.2758720080060346,
 -3.1800777150996966,
 -3.0720187889940798,
 -2.895224624607033,
 -2.7256150349148864,
 -2.2031761499150107,
 -1.9539186739046885,
 -1.4033944948450097,
 -1.4021692200257168,
 -1.2869195826546176,
 -1.2380824038222054,
 -1.0947295376203003,
 -1.0270331731418603,
 -0.720604639528179,
 -0.7141415603186311,
 -0.6514552392635018,
 -0.42880725718575563,
 -0.297602640308475,
 -0.18629952899759936,
 -0.06921267469059213,
 0.013770034479445362,
 0.1994965439631674,
 0.510716253646467,
 0.5956883994817788,
 0.7651051085261975,
 1.0274270926323275,
 1.035101940944543,
 1.0884514567225545,
 1.0942423350107828,
 1.1776415337079364,
 1.3293193010072126,
 1.367215013304156,
 1.6609535972068215,
 1.7403939942452626,
 2.312646007426293,
 2.3934691709729643,
 2.421780892431059,
 2.5377455921060412,
 3.0274990988475494,
 3.1598534488009706,
 3.265145573402394,
 3.351920480038732

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0018638299330187163,
 0.0027034952522835584,
 0.012344403114275376,
 0.013978601003949414,
 0.02572781747273863,
 0.036408260656042434,
 0.03992235513839192,
 0.04427632201982002,
 0.052390132412964176,
 0.061478685187859275,
 0.09946563217679115,
 0.12412669496904367,
 0.19727800885657962,
 0.19747211460995498,
 0.21637465977471457,
 0.22476994747092882,
 0.2507287222677484,
 0.2636596895861436,
 0.3272598510842731,
 0.3286843534413908,
 0.34266167745409615,
 0.394411183476236,
 0.4261436420194316,
 0.4535593600482968,
 0.48270373543679984,
 0.5034424542252834,
 0.5497093804758222,
 0.6249743660278134,
 0.6446692616295105,
 0.6824610804835625,
 0.7364167801067518,
 0.737903817229266,
 0.7480900086676346,
 0.749179738868811,
 0.764523480297396,
 0.790728016901058,
 0.7969298243986354,
 0.840365970605987,
 0.8507371031452629,
 0.9099189744624772,
 0.9163279375317496,
 0.9184731975108078,
 0.9267459266918066,
 0.9538010968265984,
 0.9592952242975862,
 0.9632135500745599,
 0.9661676681

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.283256      0.001864
1 -5.910503      0.002703
2 -4.382131      0.012344
3 -4.256150      0.013979
4 -3.634118      0.025728

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'data=%{x}<br>sigmoid_data=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': ('AI8v7A0iGcDKQHHOWqQXwFS3EmxNhx' ... 'oeNhBAhb3eShyVFUA7yN/8/woYQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('RUTjJniJXj9HvDD2oyVmP+PMUL0FSI' ... 'gcdO8/iFMlYwHb7z8c4oHN9evvPw=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'height': 400,
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Sigmoid Function'},
               'width': 700,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'data'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'sigmoid_data'}}}
})

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [14]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-5.428121577589309,
 -4.401145232309522,
 -3.6678373589151265,
 -3.6453338923109166,
 -3.5371756169031836,
 -3.4427588009224332,
 -3.178186126419987,
 -2.8585616000702996,
 -2.722331709868845,
 -2.7107263000917063,
 -2.7089693609603005,
 -2.2833219165262433,
 -2.2520037431481144,
 -2.019200752636164,
 -1.9806891266706117,
 -1.7223264154079023,
 -1.7111423536781134,
 -1.6521326950106976,
 -1.6264631483285301,
 -1.4993709180083556,
 -1.495953752622376,
 -1.4453914974482795,
 -1.3742380450867657,
 -1.3547439898678535,
 -1.2610003924132844,
 -1.2305016962889963,
 -1.2216452627535246,
 -1.1632694340469922,
 -1.0663322545888558,
 -1.0469389075851545,
 -1.0365341271646642,
 -0.8003409825417327,
 -0.7906815793988254,
 -0.7510100707031716,
 -0.7138987251032497,
 -0.6516607654073271,
 -0.642443268721837,
 -0.5936540508717126,
 -0.5099342971066552,
 -0.4908895466210706,
 -0.3676198385197867,
 -0.3320229111521031,
 -0.33022869680024547,
 -0.2941927029362692,
 -0.29002412386926996,
 -0.27458570151

In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9999614330651335,
 -0.9996992687836159,
 -0.998697121444348,
 -0.998637184153367,
 -0.9983083488864336,
 -0.9979571152679811,
 -0.9965347109142432,
 -0.9934432470892373,
 -0.9913985650187342,
 -0.9911974726281316,
 -0.9911666240638513,
 -0.9794282355257341,
 -0.9781130368135595,
 -0.9653593149490923,
 -0.9626375465659233,
 -0.938142551807404,
 -0.9367875503247372,
 -0.9291496983308293,
 -0.9255562455050027,
 -0.9050345096002764,
 -0.904414386130157,
 -0.8947778443452936,
 -0.8796544548060402,
 -0.8751683837364952,
 -0.8513396730275093,
 -0.8427247862235006,
 -0.8401388267257008,
 -0.8221025124359533,
 -0.7880753877496267,
 -0.7806134185205491,
 -0.7765157331130395,
 -0.6642273551593509,
 -0.6587949757555865,
 -0.6357511596860694,
 -0.613115802001016,
 -0.572786921004365,
 -0.5665608501789351,
 -0.532518549426455,
 -0.4698940048438427,
 -0.4549221693191287,
 -0.3519080576832004,
 -0.3203372797003517,
 -0.318726256186501,
 -0.2859891942701818,
 -0.28215701612651806,
 -0.2678866576474

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -5.428122  -0.999961
1 -4.401145  -0.999699
2 -3.667837  -0.998697
3 -3.645334  -0.998637
4 -3.537176  -0.998308

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'data=%{x}<br>tanh_data=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': ('ANW5gGW2FcDm3NbQxZoRwCqz/By7Vw' ... 'OJEkMQQNP6pCqHvhRAv3GThSNoFUA='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('VdWIHq//778EWChSif3vv2HPZqpT9e' ... 'QXLvvvP00Lv8B8/+8/Vycrw6H/7z8='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'height': 400,
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Tanh Function'},
               'width': 700,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'data'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'tanh_data'}}}
})

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [19]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [20]:
data = np.random.randn(4, 5)
data

array([[ 0.717596, -0.181039, -0.38039 , -1.452597, -0.682648],
       [-0.843634,  0.604159,  0.044109, -0.694413,  0.561245],
       [ 1.196999,  2.933718, -0.38806 , -1.006327, -0.398842],
       [-1.323561,  1.25693 ,  0.648179, -0.518517,  1.759745]])

In [21]:
np.exp(data)

array([[ 2.049501,  0.834403,  0.683594,  0.233962,  0.505277],
       [ 0.430145,  1.829713,  1.045097,  0.499368,  1.752854],
       [ 3.310168, 18.797395,  0.678372,  0.365559,  0.671096],
       [ 0.266186,  3.514615,  1.912056,  0.595403,  5.810953]])

In [22]:
np.sum(np.exp(data), axis=0)

array([ 6.056   , 24.976126,  4.319118,  1.694291,  8.740181])

In [23]:
np.exp(data) / np.sum(np.exp(data), axis=0)

array([[0.338425, 0.033408, 0.158272, 0.138088, 0.057811],
       [0.071028, 0.073258, 0.24197 , 0.294735, 0.200551],
       [0.546593, 0.752615, 0.157062, 0.215759, 0.076783],
       [0.043954, 0.140719, 0.442696, 0.351417, 0.664855]])

In [24]:
results = softmax(data)
results

array([[0.338425, 0.033408, 0.158272, 0.138088, 0.057811],
       [0.071028, 0.073258, 0.24197 , 0.294735, 0.200551],
       [0.546593, 0.752615, 0.157062, 0.215759, 0.076783],
       [0.043954, 0.140719, 0.442696, 0.351417, 0.664855]])

In [25]:
np.sum(results, axis=0)

array([1., 1., 1., 1., 1.])